export const ACTION_ERROR = 'ACTION_ERROR';

// Login Actions
export const USER_LOGIN_SET_REFERRER = 'USER_LOGIN_SET_REFERRER';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILED = 'USER_LOGIN_REQUEST';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_NOT_LOGGED_IN = 'USER_NOT_LOGGED_IN';

// Home actions
export const FETCHING_USERS = 'FETCHING_USERS';
export const RECEIVED_USERS = 'RECEIVED_USERS';
