export default [
	{
		id: 1,
		title: "Game Theory: A Class on Strategy",
		subtitle: "This lesson will investigate game theory and its various principles and application in the real world.",
		author: "Project BEST ",
		description: "Game theory is a field (a branch of mathematics, logic, and psychology) that aims to discern certain principles in interactions. This lesson will investigate game theory and its various principles and application in the real world.",
		link: "https://lessons.hackinabox.tech/files/Game_Theory.pdf",
		image: "https://lessons.hackinabox.tech/img/gametheory.png",
		grade: "6-12",
		subject: "Math",
	},
	{
		id: 2,
		title: "Illusions: Vision and Perception",
		subtitle: "Optical illusions can be used to help us understand the inner workings of perception",
		author: "Project BEST ",
		description: "Vision and perception are very complicated processes, and optical illusions can be used to help understand the inner workings of perception. In this lesson, students will engage with various optical illusions and dissect them to understand the fundamental happenings in each.",
		link: "https://lessons.hackinabox.tech/files/Illusions.pdf",
		image: "https://lessons.hackinabox.tech/img/illusionAndPerception.png",
		grade: "4-8",
		subject: "Math",
	},
	{
		id: 3,
		title: "Popsicle Structures",
		subtitle: "Using the basics of architecture, students work together in small team to build the tallest structure",
		author: "Project BEST ",
		description: "Students will learn how to create sound structures with using the basics of architecture. Students work together in small team to build the tallest structure. Students should use triangles as well as cross beams and should draw out a basic plan before starting to build",
		link: "https://lessons.hackinabox.tech/files/Popsicle_Structures.pdf",
		image: "https://lessons.hackinabox.tech/img/popsicleStructures.png",
		grade: "6-12",
		subject: "Science",
	},
	{
		id: 4,
		title: "Art in Public Spaces",
		subtitle: "Public art and the use of context and content",
		author: "Stanford Design for America Team",
		description: "The use of content and context in public art, getting students to view the ordinary with an artist’s eye",
		link: "https://lessons.hackinabox.tech/files/Art_Public.pdf",
		image: "https://lessons.hackinabox.tech/img/ArtinPublicSpaces.png",
		grade: "8-9",
		subject: "Art, Architecture, Social Studies, History",
	},
	{
		id: 5,
		title: "Remix- Computer Science",
		subtitle: "A look into the use of remixing, an important concept in Computer Science. Fits into the hour of code. ",
		author: "Jennifer Latimer, Code.org Teacher of the Month",
		description: "This lesson provides students with an application of remixing, an important concept in computer science.",
		image: "https://lessons.hackinabox.tech/img/remix.png",
		grade: "5",
		subject: "CS - Hour of Code",
	},
	{
		id: 6,
		title: "Rights Constructor ",
		subtitle: "Interactive activity with the Bill of Rights and its modern day implications",
		author: "Stanford Design for America Team",
		description: "This lesson teaches the bill of rights as well as the historical reasons and context behind it. It also covers the modern connotations of these amendments.",
		link: "https://lessons.hackinabox.tech/files/Rights_Constructor.pdf",
		image: "https://lessons.hackinabox.tech/img/rights.png",
		grade: "8-9",
		subject: "American History, Government, Constitutional Law",
	},
	{
		id: 7,
		title: "Rube Goldberg Machine: How a Bill Becomes a Law",
		subtitle: "A fun, interactive visualization of how a bill becomes a law",
		author: "Stanford Design for America Team",
		description: "This lesson creates a fun, innovative environment for students to learn about the process of passing a bill. The abstract and creative thinking skills in their choice of material and mechanism help them tie facts and ideas to visuals.",
		link: "https://lessons.hackinabox.tech/files/Rude_Goldberg.pdf",
		grade: "8-9",
		subject: "American History, Government, Constitutional Law",
	},
	{
		id: 8,
		title: "Shakespeare in Modern Day",
		subtitle: "A glimpse into Shakespeare's style and wordplay",
		author: "Stanford Design for America Team",
		description: "This lesson gives student both an increased retention and understanding of Shakespearean phrasing as well as an insight into the work of translators. Hopefully this plan will help students gain an appreciation for Shakespeare’s style and wordplay.",
		image: "https://lessons.hackinabox.tech/img/Shakespeare.png",
		grade: "8-9",
		subject: "English, Literature",
	},
	{
		id: 9,
		title: "Understanding War: The Battle Plan",
		subtitle: "A reenactment of one of the most tumultuous, defining times in national history...enacted via water balloons!",
		description: "Stanford Design for America Team",
		link: "This lesson will help students gain an understanding of the most tumultuous, defining time in national history. It will focus on the geography and physicality of the American Revolution and its major battles, and also on the social dynamics of war — relationships between soldiers and generals, reporters and the public",
		grade: "8-9",
		subject: "American History, Government, Constitutional Law",
	},
	{
		id: 10,
		title: "Ruby Says Robot Game",
		subtitle: "A basic challenge to get students thinking about simple instructions and sequences, or in coding terms, creating algorithms.",
		author: "Piper EDU",
		description: "This lesson is an intro to computational thinking, and students will create quick basic commands for real world problems then link them to coding concepts.",
		link: "https://docs.google.com/document/d/1dw6KJpZK79QFxwjAnmduvBzMUS8XwVo4k8BXSSJqtqw/edit#heading=h.w02bwl1lj1m",
		image: "https://cdn.shopify.com/s/files/1/0925/6256/t/54/assets/newkit-min.png?7946576747404267751",
		grade: "3-8,",
		subject: "CS",
	},
	{
		id: 11,
		title: "Loops, Sequences, and Events, Oh My!",
		subtitle: "A dive into computational tinkering through the Piper Kit!",
		author: "Piper EDU",
		description: "The goal of this lesson is for students to refresh their learning of Piper hardware and electronic component and dive into computational tinkering! The first three projects challenge the students to practice keys electronic and programming skills, but extend understanding to solve problems by coding behaviors in the language of Piper Code including making lights blink, changing the sequence of the lights based on pivoting questions, and orchestrate cause and effect.",
		link: "https://docs.google.com/document/d/1dw6KJpZK79QFxwjAnmduvBzMUS8XwVo4k8BXSSJqtqw/edit#heading=h.95kdm12ecgob",
		image: "https://cdn.shopify.com/s/files/1/0925/6256/t/54/assets/newkit-min.png?7946576747404267751",
		grade: "3-8",
		subject: "CS",
	},
	{
		id: 12,
		title: "Light and Sound Inventions",
		subtitle: "Adding on hardware and interactive functions ",
		author: "Piper EDU",
		description: "Students will build a random button controller for a custom made game with 4 different colored LED lights and a buzzer",
		link: "https://docs.google.com/document/d/1dw6KJpZK79QFxwjAnmduvBzMUS8XwVo4k8BXSSJqtqw/edit#heading=h.oyca6a37d1c1",
		image: "https://cdn.shopify.com/s/files/1/0925/6256/t/54/assets/newkit-min.png?7946576747404267751",
		grade: "3-8",
		subject: "CS",
	},
];
